### ISSUE TITLE
day11 运行代码时邮箱密码（授权码）无法输入

### ISSUE THREAD

**Issue by cjh20040088** [selfteaching/selfteaching-python-camp#2265]
在运行day11作业的代码时，需要输入邮箱名和密码，但是密码处于无法输入的状态？
截图如下：
输入发件人邮箱：xxx@163.com
输入发件人邮箱密码：
输入收件人邮箱：pythoncamp@163.com
Traceback (most recent call last):
  File "c:/Users/陈建辉/Documents/GitHub/selfteaching-python-camp/19100402/cjh20040088/d11/main.py", line 24, in <module>
    yag.send(to=recipients,subject=subject,contents=result)
  File "C:\Python37\lib\site-packages\yagmail\sender.py", line 147, in send
    self.login()
  File "C:\Python37\lib\site-packages\yagmail\sender.py", line 246, in login
    self._login(self.credentials)
  File "C:\Python37\lib\site-packages\yagmail\sender.py", line 204, in _login
    self.smtp.login(self.user, password)
  File "C:\Python37\lib\smtplib.py", line 694, in login
    self.ehlo_or_helo_if_needed()
  File "C:\Python37\lib\smtplib.py", line 603, in ehlo_or_helo_if_needed
    raise SMTPHeloError(code, resp)
smtplib.SMTPHeloError: (500, b'Error: bad syntax')

**Comment by yjz111** [comment]
提示语法错误，不是你无法输入pwd，而是没显示而已~ 你得知道为啥引入getpass模块吧？为什么不用input？为了安全，当代码运行到 getpass.getpass('请输入密码:')时，程序会提示你输入密码，此时的效果就跟Linux上面输入密码的效果一样，屏幕上不会显示密码内容，看起来就像是键盘失效了一样。不过不用担心，盲输就可以了。输入完成以后，按下回车键，密码就被保存到 password变量中了。

**Comment by realcaiying** [comment]
`smtplib.SMTPHeloError: (500, b'Error: bad syntax')`

从这个错误来看，应该是调用 yagmail 函数时，参数有问题。 可以把完成的代码贴出来看下。
