### ISSUE TITLE
day11 ImportError: DLL load failed？这个怎么办？

### ISSUE THREAD

**Issue by congboqiu** [selfteaching/selfteaching-python-camp#2282]
在Anaconda prompt下，完成安装pip install yagmail ;pip install pyquery;pip install requests. 并更新到最新版本，也重启机器，再运行requests调用以及pyquery提取时候，就出现了：
   File "c:/Users/win10/Documents/GitHub/selfteaching-python-camp/19100401/congboqiu/d11/main.py", line 13, in <module>
    from pyquery import PyQuery
  File "C:\ProgramData\Anaconda3\lib\site-packages\pyquery\__init__.py", line 7, in <module>
    from .pyquery import PyQuery  # NOQA
  File "C:\ProgramData\Anaconda3\lib\site-packages\pyquery\pyquery.py", line 10, in <module>
    from lxml import etree
ImportError: DLL load failed: 找不到指定的模块 @realcaiying @shengzhulst

**Comment by congboqiu** [comment]
而且，也试过把pillow升到最新版本Name: Pillow
Version: 5.3.0。

**Comment by shengzhulst** [comment]
pillow和那三个包是没有关系的，你去pip upgrade lxml一下试一试

**Comment by congboqiu** [comment]
Could not install packages due to an EnvironmentError: [WinError 5] 拒绝访问。: 'c:\\programdata\\anaconda3\\lib\\site-packages\\lxml-4.2.5.dist-info\\installer'
Consider using the `--user` option or check the permissions.

**Comment by congboqiu** [comment]
@shengzhulst 在教练帮助下解决了1.ImportError: DLL load failed: 2.[WinError 5] 拒绝访问。3.现在又来了SSL module 不可用的问题：
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "c:/Users/win10/Documents/GitHub/selfteaching-python-camp/19100401/congboqiu/d11/main.py", line 16, in <module>
    response = requests.get("https://mp.weixin.qq.com/s/pLmuGoc4bZrMNl7MSoWgiA")
  File "C:\ProgramData\Anaconda3\lib\site-packages\requests\api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\requests\api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\requests\sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\requests\sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\requests\adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='mp.weixin.qq.com', port=443): Max retries exceeded with url: /s/pLmuGoc4bZrMNl7MSoWgiA (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available."))
PS C:\Users\win10\Documents\GitHub\selfteaching-python-camp>

**Comment by shengzhulst** [comment]
方法一：关闭SSL认证，response = requests.get('http://www.baidu.com/',  verify=False)
方法二：http://docs.python-requests.org/zh_CN/latest/user/advanced.html#ssl
事实上，很有可能是你电脑上安装了其他的SSL证书，导致requests出现这种问题，你也可以把你的SSL包删了重新安装一次试一下

**Comment by congboqiu** [comment]
最后，Windows10 python中调用SSL模块不可用的问题可以参考下面的方法：https://blog.csdn.net/qq_41761293/article/details/86988511；
https://blog.csdn.net/zfy1355/article/details/87204686

**Comment by srvz** [comment]
> @shengzhulst 在教练帮助下解决了1.ImportError: DLL load failed: 2.[WinError 5] 拒绝访问。3.现在又来了SSL module 不可用的问题：
> During handling of the above exception, another exception occurred:
> Traceback (most recent call last):
> File "c:/Users/win10/Documents/GitHub/selfteaching-python-camp/19100401/congboqiu/d11/main.py", line 16, in 
> response = requests.get("https://mp.weixin.qq.com/s/pLmuGoc4bZrMNl7MSoWgiA")
> File "C:\ProgramData\Anaconda3\lib\site-packages\requests\api.py", line 75, in get
> return request('get', url, params=params, **kwargs)
> File "C:\ProgramData\Anaconda3\lib\site-packages\requests\api.py", line 60, in request
> return session.request(method=method, url=url, **kwargs)
> File "C:\ProgramData\Anaconda3\lib\site-packages\requests\sessions.py", line 533, in request
> resp = self.send(prep, **send_kwargs)
> File "C:\ProgramData\Anaconda3\lib\site-packages\requests\sessions.py", line 646, in send
> r = adapter.send(request, **kwargs)
> File "C:\ProgramData\Anaconda3\lib\site-packages\requests\adapters.py", line 514, in send
> raise SSLError(e, request=request)
> requests.exceptions.SSLError: HTTPSConnectionPool(host='mp.weixin.qq.com', port=443): Max retries exceeded with url: /s/pLmuGoc4bZrMNl7MSoWgiA (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available."))
> PS C:\Users\win10\Documents\GitHub\selfteaching-python-camp>

https://github.com/conda/conda/issues/8273
